# Criacao de DOCKERFILE
FROM python:3.9-slim
WORKDIR /app
COPY . /app

# Instala dependencias de requirements.txt
#RUN pip install --no-cache-dir -r requirements.txt

# Utiliza a porta 8080
EXPOSE 8888

# Define variavel de ambiente do flask
ENV FLASK_APP=sqlite_db.py

# Roda o sqlite_db.py
CMD ["flask", "run", "--host=0.0.0.0", "--port=8888"]
